version: '2'
services:

  web:
    image: web
    container_name: web
    ports:
      - "5000:5000"
    networks: 
      - fbid

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks: 
      - fbid

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=flight_delay_classification_request:1:1 
    networks: 
      - fbid

  mongo:
    image: mongo:4.2
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ~/Desktop/BIGDATA_Project/practica_big_data_2019-master/:/prediccion_vuelos/
    networks:
      - fbid
  
  spark-master:
    image: bde2020/spark-master:2.4.4-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "constraint:node==spark-master"
    volumes:
      - ~/Desktop/BIGDATA_Project/practica_big_data_2019-master/:/prediccion_vuelos/
    networks: 
      - fbid

  spark-worker-1:
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==spark-master"
    volumes:
      - ~/Desktop/BIGDATA_Project/practica_big_data_2019-master/:/prediccion_vuelos/
    networks: 
      - fbid

networks: 
  fbid: